//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.GSB.Share.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapper.GSB.Share.Resource.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام درخواست در زمان ارسال اطلاعات به سرور مرکز داده بیمه مرکزی با خطا رو برو شده است..
        /// </summary>
        public static string An_error_occurred_while_performing_the_operation_during_the_data_transmission_to_the_Central_Insurance_Repository {
            get {
                return ResourceManager.GetString("An error occurred while performing the operation during the data transmission to " +
                        "the Central Insurance Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام درخواست در زمان ارسال اطلاعات به سرور GSB با خطا رو برو شده است..
        /// </summary>
        public static string An_error_occurred_while_performing_the_operation_during_the_data_transmission_to_the_GSB_server {
            get {
                return ResourceManager.GetString("An error occurred while performing the operation during the data transmission to " +
                        "the GSB server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست مورد نظر با موفقیت انجام شده است..
        /// </summary>
        public static string The_operation_has_done_sucessfully {
            get {
                return ResourceManager.GetString("The operation has done sucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست مورد نظر در حال انجام می‌باشد..
        /// </summary>
        public static string The_operation_is_in_progress {
            get {
                return ResourceManager.GetString("The operation is in progress", resourceCulture);
            }
        }
    }
}
