//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.GSB.Share.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Names {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapper.GSB.Share.Resource.Names", typeof(Names).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات صندوق های مرتبط با بیمه شده.
        /// </summary>
        public static string AccountVO {
            get {
                return ResourceManager.GetString("AccountVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سریال مرتبط با صندوق یا خدمت.
        /// </summary>
        public static string AccountVO_AccountID {
            get {
                return ResourceManager.GetString("AccountVO.AccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت اعتباری صندوق یا خدمت.
        /// </summary>
        public static string AccountVO_AccountStatus {
            get {
                return ResourceManager.GetString("AccountVO.AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نوع صندوق – خدمت.
        /// </summary>
        public static string AccountVO_AccountType {
            get {
                return ResourceManager.GetString("AccountVO.AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع اعتبار.
        /// </summary>
        public static string AccountVO_ActiveFrom {
            get {
                return ResourceManager.GetString("AccountVO.ActiveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان اعتبار.
        /// </summary>
        public static string AccountVO_ActiveTo {
            get {
                return ResourceManager.GetString("AccountVO.ActiveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string AccountVO_CreateDate {
            get {
                return ResourceManager.GetString("AccountVO.CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اولین ثبت نام.
        /// </summary>
        public static string AccountVO_InitiateDate {
            get {
                return ResourceManager.GetString("AccountVO.InitiateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سرویس وب .
        /// </summary>
        public static string ApiServiceSetting {
            get {
                return ResourceManager.GetString("ApiServiceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظمیات سرویس GetToken.
        /// </summary>
        public static string ApiServiceSetting_GetToken {
            get {
                return ResourceManager.GetString("ApiServiceSetting.GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظمیات سرویس SendPersonInfo.
        /// </summary>
        public static string ApiServiceSetting_SendPersonInfo {
            get {
                return ResourceManager.GetString("ApiServiceSetting.SendPersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظمیات سرویس SendPersonSupplimantryInfo.
        /// </summary>
        public static string ApiServiceSetting_SendPersonSupplimantryInfo {
            get {
                return ResourceManager.GetString("ApiServiceSetting.SendPersonSupplimantryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواسته شده.
        /// </summary>
        public static string Asked {
            get {
                return ResourceManager.GetString("Asked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختصاص دهنده.
        /// </summary>
        public static string Assigner {
            get {
                return ResourceManager.GetString("Assigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت عملیات.
        /// </summary>
        public static string AUDIT_CHANGE {
            get {
                return ResourceManager.GetString("AUDIT_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز دسترسی.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده ها به استاندارد بیمه.
        /// </summary>
        public static string DATA_INSURANCE_FORMAT {
            get {
                return ResourceManager.GetString("DATA.INSURANCE.FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایگاه داده.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درج اطلاعات در سرور DDR.
        /// </summary>
        public static string DDR_Insert {
            get {
                return ResourceManager.GetString("DDR.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شخص یا فرد در openEHR.
        /// </summary>
        public static string DDR_Person {
            get {
                return ResourceManager.GetString("DDR.Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات بیمه فرد در openEHR.
        /// </summary>
        public static string DDR_Relationship {
            get {
                return ResourceManager.GetString("DDR.Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات در سرور DDR.
        /// </summary>
        public static string DDR_Update {
            get {
                return ResourceManager.GetString("DDR.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار کد.
        /// </summary>
        public static string DoCodedText_Code {
            get {
                return ResourceManager.GetString("DoCodedText.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ترمینولوژِی کد.
        /// </summary>
        public static string DoCodedText_Terminology {
            get {
                return ResourceManager.GetString("DoCodedText.Terminology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نمایشی کد.
        /// </summary>
        public static string DoCodedText_Value {
            get {
                return ResourceManager.GetString("DoCodedText.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت خواندن.
        /// </summary>
        public static string FOR_READ {
            get {
                return ResourceManager.GetString("FOR_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت نوشتن.
        /// </summary>
        public static string FOR_WRITE {
            get {
                return ResourceManager.GetString("FOR_WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  دریافت توکن.
        /// </summary>
        public static string GetToken {
            get {
                return ResourceManager.GetString("GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع شناسه.
        /// </summary>
        public static string IdType {
            get {
                return ResourceManager.GetString("IdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای داخلی سرور.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر کننده.
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت پرونده.
        /// </summary>
        public static string LIFECYCLE_STATE {
            get {
                return ResourceManager.GetString("LIFECYCLE_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبادل داده های پرونده الکترونیکی سلامت.
        /// </summary>
        public static string MessageIdentifierVO {
            get {
                return ResourceManager.GetString("MessageIdentifierVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه یگانه مرکز ارائه دهنده خدمت بهداشت درمانی.
        /// </summary>
        public static string MessageIdentifierVO_HealthCareFacilityID {
            get {
                return ResourceManager.GetString("MessageIdentifierVO_HealthCareFacilityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه یکتای داده پیام ارسالی به هاب بیمه مرکزی.
        /// </summary>
        public static string MessageIdentifierVO_MessageUID {
            get {
                return ResourceManager.GetString("MessageIdentifierVO.MessageUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه منحصر به فرد ثبت اطلاعات بیمه شده در هاب بیمه مرکزی.
        /// </summary>
        public static string MessageIdentifierVO_RegisterUID {
            get {
                return ResourceManager.GetString("MessageIdentifierVO.RegisterUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه یگانه سیستم نرم‌افزاری ارسال‌کننده داده.
        /// </summary>
        public static string MessageIdentifierVO_SystemID {
            get {
                return ResourceManager.GetString("MessageIdentifierVO.SystemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه یگانه دانشگاه ناظر ارائه دهنده خدمات پزشکی.
        /// </summary>
        public static string MessageIdentifierVO_UniversityID {
            get {
                return ResourceManager.GetString("MessageIdentifierVO_UniversityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه سند.
        /// </summary>
        public static string MessageIdentifierVO_Version {
            get {
                return ResourceManager.GetString("MessageIdentifierVO.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت ارسال پرونده.
        /// </summary>
        public static string MessageIdentifierVO_VersionLifecycleState {
            get {
                return ResourceManager.GetString("MessageIdentifierVO_VersionLifecycleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دقیقه.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیمه شده.
        /// </summary>
        public static string PersonInfoVO {
            get {
                return ResourceManager.GetString("PersonInfoVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد بیمه شده.
        /// </summary>
        public static string PersonInfoVO_BirthDate {
            get {
                return ResourceManager.GetString("PersonInfoVO.BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهرستان بیمه شده.
        /// </summary>
        public static string PersonInfoVO_City {
            get {
                return ResourceManager.GetString("PersonInfoVO.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بیمه شده.
        /// </summary>
        public static string PersonInfoVO_FirstName {
            get {
                return ResourceManager.GetString("PersonInfoVO.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس بیمه شده.
        /// </summary>
        public static string PersonInfoVO_FullAddress {
            get {
                return ResourceManager.GetString("PersonInfoVO.FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string PersonInfoVO_Gender {
            get {
                return ResourceManager.GetString("PersonInfoVO.Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی بیمه شده.
        /// </summary>
        public static string PersonInfoVO_LastName {
            get {
                return ResourceManager.GetString("PersonInfoVO.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تاهل فرد.
        /// </summary>
        public static string PersonInfoVO_MaritalStatus {
            get {
                return ResourceManager.GetString("PersonInfoVO_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه.
        /// </summary>
        public static string PersonInfoVO_Mobile {
            get {
                return ResourceManager.GetString("PersonInfoVO.Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه بیمه شده.
        /// </summary>
        public static string PersonInfoVO_MobileNumber {
            get {
                return ResourceManager.GetString("PersonInfoVO.MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی بیمه شده.
        /// </summary>
        public static string PersonInfoVO_NationalCode {
            get {
                return ResourceManager.GetString("PersonInfoVO.NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملیت فرد.
        /// </summary>
        public static string PersonInfoVO_Nationality {
            get {
                return ResourceManager.GetString("PersonInfoVO_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ملی فرد یا شناسه اتباع بیگانه یا پاسپورت.
        /// </summary>
        public static string PersonInfoVO_PersonID {
            get {
                return ResourceManager.GetString("PersonInfoVO.PersonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر بیمه شده.
        /// </summary>
        public static string PersonInfoVO_PictureB64 {
            get {
                return ResourceManager.GetString("PersonInfoVO.PictureB64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string PersonInfoVO_PostalCode {
            get {
                return ResourceManager.GetString("PersonInfoVO.PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان بیمه شده.
        /// </summary>
        public static string PersonInfoVO_Province {
            get {
                return ResourceManager.GetString("PersonInfoVO.Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیمه نامه و بیمه شده.
        /// </summary>
        public static string PersonInsurance {
            get {
                return ResourceManager.GetString("PersonInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ثبت/الحاقیه بیمه شده یا زمان ارا.
        /// </summary>
        public static string PersonInsurance_ServiceDateTime {
            get {
                return ResourceManager.GetString("PersonInsurance.ServiceDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هماهنگ کننده و خلاصه اطلاعات بیمه نامه.
        /// </summary>
        public static string PersonInsuranceDataCoordinator {
            get {
                return ResourceManager.GetString("PersonInsuranceDataCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین نسخه از این نمونه اطلاعات فردی و بیمه نامه.
        /// </summary>
        public static string PersonInsuranceDataCoordinator_PersonInsuranceVersion {
            get {
                return ResourceManager.GetString("PersonInsuranceDataCoordinator.PersonInsuranceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه منحصر بفرد صادر شده توسط سازمان بیمه گر.
        /// </summary>
        public static string PersonInsuranceDataCoordinator_Shebad {
            get {
                return ResourceManager.GetString("PersonInsuranceDataCoordinator.Shebad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت فعلی سند بیمه.
        /// </summary>
        public static string PersonInsuranceDataCoordinator_Status {
            get {
                return ResourceManager.GetString("PersonInsuranceDataCoordinator.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت خلاصه اطلاعات وضعیت بیمه نامه بر اساس شناسه.
        /// </summary>
        public static string PersonInsuranceInfoByPersonIdQuery {
            get {
                return ResourceManager.GetString("PersonInsuranceInfoByPersonIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش وضعیت درخواست های ثبت و ویرایش اطلاعات بیمه نامه.
        /// </summary>
        public static string PersonInsuranceStatusByDateQuery {
            get {
                return ResourceManager.GetString("PersonInsuranceStatusByDateQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت درخواست ثبت یا ویرایش اطلاعات بیمه شده و بیمه نام.
        /// </summary>
        public static string PersonInsuranceStatusByRegisterUIDQuery {
            get {
                return ResourceManager.GetString("PersonInsuranceStatusByRegisterUIDQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیمه نامه.
        /// </summary>
        public static string PersonPolicyVO {
            get {
                return ResourceManager.GetString("PersonPolicyVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات صندوق های مرتبط با بیمه شده.
        /// </summary>
        public static string PersonPolicyVO_Account {
            get {
                return ResourceManager.GetString("PersonPolicyVO.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک.
        /// </summary>
        public static string PersonPolicyVO_BankAcc {
            get {
                return ResourceManager.GetString("PersonPolicyVO_BankAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان بیمه‌گر پایه.
        /// </summary>
        public static string PersonPolicyVO_BaseInsurer {
            get {
                return ResourceManager.GetString("PersonPolicyVO_BaseInsurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه محل صدور بیمه نامه.
        /// </summary>
        public static string PersonPolicyVO_Branch {
            get {
                return ResourceManager.GetString("PersonPolicyVO_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد و عنوان شهر محل صدور بیمه.
        /// </summary>
        public static string PersonPolicyVO_CityBranch {
            get {
                return ResourceManager.GetString("PersonPolicyVO.CityBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رایانه بیمه شده.
        /// </summary>
        public static string PersonPolicyVO_CompanyInsuredId {
            get {
                return ResourceManager.GetString("PersonPolicyVO.CompanyInsuredId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رایانه بیمه نامه.
        /// </summary>
        public static string PersonPolicyVO_CompanyPolicyId {
            get {
                return ResourceManager.GetString("PersonPolicyVO.CompanyPolicyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع قرارداد بیمه شده اصلی.
        /// </summary>
        public static string PersonPolicyVO_ContractType {
            get {
                return ResourceManager.GetString("PersonPolicyVO_ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ فوت.
        /// </summary>
        public static string PersonPolicyVO_DeathDate {
            get {
                return ResourceManager.GetString("PersonPolicyVO_DeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع اعتبار بیمه شده.
        /// </summary>
        public static string PersonPolicyVO_EffectiveDate {
            get {
                return ResourceManager.GetString("PersonPolicyVO.EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق بيمه فرد.
        /// </summary>
        public static string PersonPolicyVO_InsuranceBox {
            get {
                return ResourceManager.GetString("PersonPolicyVO.InsuranceBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان اعتبار بیمه.
        /// </summary>
        public static string PersonPolicyVO_InsuranceExpirationDate {
            get {
                return ResourceManager.GetString("PersonPolicyVO.InsuranceExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع بیمه شده.
        /// </summary>
        public static string PersonPolicyVO_InsuredType {
            get {
                return ResourceManager.GetString("PersonPolicyVO.InsuredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شرکت بیمه تکمیلی/فول درمان.
        /// </summary>
        public static string PersonPolicyVO_Insurer {
            get {
                return ResourceManager.GetString("PersonPolicyVO.Insurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بیمه گذار بیمه نامه.
        /// </summary>
        public static string PersonPolicyVO_InsurerName {
            get {
                return ResourceManager.GetString("PersonPolicyVO.InsurerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ملی بیمه گذار حقوقی/کدملی بیمه گذار حقیقی.
        /// </summary>
        public static string PersonPolicyVO_InsurerNationalCode {
            get {
                return ResourceManager.GetString("PersonPolicyVO_InsurerNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع پوشش.
        /// </summary>
        public static string PersonPolicyVO_IsCoverageUnlimited {
            get {
                return ResourceManager.GetString("PersonPolicyVO_IsCoverageUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رایانه طرح بیمه نامه در  شرکت بیمه تکمیلی/فول درمان.
        /// </summary>
        public static string PersonPolicyVO_PlanId {
            get {
                return ResourceManager.GetString("PersonPolicyVO_PlanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ صدور بیمه نامه درمان.
        /// </summary>
        public static string PersonPolicyVO_PolicyIssueDate {
            get {
                return ResourceManager.GetString("PersonPolicyVO_PolicyIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره چاپی بیمه نامه.
        /// </summary>
        public static string PersonPolicyVO_PolicyPrintNumber {
            get {
                return ResourceManager.GetString("PersonPolicyVO.PolicyPrintNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ورودی بیمه نامه.
        /// </summary>
        public static string PersonPolicyVO_PolicyType {
            get {
                return ResourceManager.GetString("PersonPolicyVO.PolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد یکتای بیمه نامه.
        /// </summary>
        public static string PersonPolicyVO_PolicyUnqiueCode {
            get {
                return ResourceManager.GetString("PersonPolicyVO.PolicyUnqiueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد و عنوان استان محل صدور بیمه.
        /// </summary>
        public static string PersonPolicyVO_ProvinceBranch {
            get {
                return ResourceManager.GetString("PersonPolicyVO.ProvinceBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string PersonPolicyVO_RecommendationMessage {
            get {
                return ResourceManager.GetString("PersonPolicyVO.RecommendationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد و عنوان نسبت بیمه شده با سرپرست.
        /// </summary>
        public static string PersonPolicyVO_RelationType {
            get {
                return ResourceManager.GetString("PersonPolicyVO.RelationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علت درخواست.
        /// </summary>
        public static string PersonPolicyVO_RequestReason {
            get {
                return ResourceManager.GetString("PersonPolicyVO_RequestReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت بیمه شده اصلی.
        /// </summary>
        public static string PersonPolicyVO_ResponsibleGender {
            get {
                return ResourceManager.GetString("PersonPolicyVO.ResponsibleGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی/کد اتباع/شماره پاسپورت بیمه شده اصلی.
        /// </summary>
        public static string PersonPolicyVO_ResponsibleID {
            get {
                return ResourceManager.GetString("PersonPolicyVO.ResponsibleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارگاه یا اداره بیمه شده.
        /// </summary>
        public static string PersonPolicyVO_WorkShop {
            get {
                return ResourceManager.GetString("PersonPolicyVO_WorkShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آماده سازی فرا داده ها .
        /// </summary>
        public static string PrepareMetaData {
            get {
                return ResourceManager.GetString("PrepareMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خصوصیت.
        /// </summary>
        public static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ثبت اطلاعات در بیمه مرکزی.
        /// </summary>
        public static string RegisterDateInDataHub {
            get {
                return ResourceManager.GetString("RegisterDateInDataHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های سازمان مربوطه.
        /// </summary>
        public static string RELATED_ORGANIZATION_DATA {
            get {
                return ResourceManager.GetString("RELATED_ORGANIZATION_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخزن داده.
        /// </summary>
        public static string REPOSITORY {
            get {
                return ResourceManager.GetString("REPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات بیمه شده در سیستم مرکزی DDR.
        /// </summary>
        public static string SavePersonInDDR {
            get {
                return ResourceManager.GetString("SavePersonInDDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات بیمه در سیستم مرکزی DDR.
        /// </summary>
        public static string SaveRelationshipInDDR {
            get {
                return ResourceManager.GetString("SaveRelationshipInDDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانیه.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات فول درمان.
        /// </summary>
        public static string SendPersonInfo {
            get {
                return ResourceManager.GetString("SendPersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات تکمیلی.
        /// </summary>
        public static string SendPersonSupplimantryInfo {
            get {
                return ResourceManager.GetString("SendPersonSupplimantryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرور.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
