// <auto-generated />
using System;
using Mapper.GSB.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mapper.GSB.Infrastructure.Migrations
{
    [DbContext(typeof(GSBDbContext))]
    [Migration("20240215060950_GSBDatabase1.41")]
    partial class GSBDatabase141
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mapper.GSB.Domain.InsuranceDataCoordinator.PersonInsuranceDataCoordinator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CompanyInsuredId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CompositionUID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DomainModel")
                        .HasColumnType("int");

                    b.Property<int>("GSBAttemptsFailCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("GSBIgin")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("GSBRegisterID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("GSBResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsurerId")
                        .HasColumnType("int");

                    b.Property<string>("LocalId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("MessageUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("PatientUID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("PersonIdType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PersonInsuranceCreatedEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PersonInsuranceVersion")
                        .HasColumnType("int");

                    b.Property<string>("PolicyUniqueCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid>("RegisterUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShebadId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("insuranceExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("insurer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("openEHRPartyId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("openEHRPartyRelationshipId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("personIdentifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("policyType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("shebad")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("RegisterUID")
                        .HasFilter("[Status]>=4");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("RegisterUID"), new[] { "PersonIdType", "openEHRPartyId", "openEHRPartyRelationshipId", "Status", "PersonId" });

                    b.HasIndex("CreatedDate", "InsurerId");

                    b.HasIndex("PersonId", "PersonIdType")
                        .HasFilter("[Status]>=4");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PersonId", "PersonIdType"), new[] { "openEHRPartyId", "openEHRPartyRelationshipId", "Status", "RegisterUID" });

                    b.HasIndex("CreatedDate", "Status", "InsurerId");

                    b.HasIndex("PersonId", "InsurerId", "AccountID");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PersonId", "InsurerId", "AccountID"), new[] { "RegisterUID", "MessageUID", "Version" });

                    b.HasIndex("PersonId", "InsurerId", "PolicyUniqueCode");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PersonId", "InsurerId", "PolicyUniqueCode"), new[] { "RegisterUID", "MessageUID", "Version" });

                    b.ToTable("PersonInsuranceDataCoordinator", (string)null);
                });

            modelBuilder.Entity("Mapper.GSB.Infrastructure.EventStore.EventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("CorrelationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Event", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
